language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
    - $HOME/.m2
install: mvn dependency:resolve dependency:resolve-plugins
script: mvn verify