# https://docs.travis-ci.com/user/customizing-the-build
language: java
jdk: oraclejdk8
addons:
  sonarqube: true
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
    - $HOME/.m2
install: mvn dependency:resolve dependency:resolve-plugins
script: mvn verify
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} == "master" ]; then mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN; fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a7baa38f9dfc511093b7
    on_success: change
    on_failure: always
    on_start: never